name: imba
description: "Accommodation aggregating app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/
